name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '22.15.1'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --maxsockets 3
        env:
          NODE_OPTIONS: '--max-old-space-size=2048'

      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test:run
      - name: Build
        run: npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTFOLIOWEBSITE_F08F4 }}'
          channelId: live
          projectId: portfoliowebsite-f08f4
